### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by saka2909** [KoALa-MHF/koala-app#364]
Description:
The Login in Koala does not work. I can login with my account but after that I get an error with {"statusCode":500,"message":"Internal server error"} and I do not get into the app. Neither Desktop nor mobile works.

**To Reproduce**
1. Go to 'Login'
2. Login with an Account 
3. See error

**Expected behavior**
possible login

**Screenshots**
![image](https://github.com/KoALa-MHF/koala-app/assets/116176535/c76fc9c2-4cfc-4879-af99-eb1c0b3d18e8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TS-Daniel16** [comment]
@saka2909 unfortunately the mh Freiburg login does not work yet, but we can only test it on the productive server, which is why you currently see this error. We switched back an forth between the mh Freiburg IDP and OneLogin which you used before, but right now switching back is not possible. We try to get you running as soon as possible, but it might be interrupted by the "real" login tests from time to time.

**Comment by TS-Tino16** [comment]
I fixed the login on live
