### ISSUE TITLE
[FEATURE] Include Test Automation (Frontend/Server) Into Pipeline

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#8]
# Description

To ensure high quality of the KoALa app, the test automation environments created in #6 and #7 should run automatically with every merge into the main branch. Potential issues should block the creation of the deployable objects and should be reported back to development.

# Tasks

- [x] Enhance pipeline with automatic test execution
- [x] Prevent merge of faulty changes

**Comment by TS-Tino16** [comment]
Added via https://github.com/KoALa-MHF/koala-app/commit/8b72c98df72dd3aa1d9777937ab8af45b2e99f8f

**Comment by TS-Tino16** [comment]
We now test:

- npm run build
- npm run e2e:api

once the frontend tests are ready, it is easy to add them

Merge of pull requested is prevented until the required runs are finished.

Matrix test für current node version + upcoming (so that we can check if the current state works with the next node version) -> only current node version tests are required to pass
